name: Deploy to EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy server code
    runs-on: [self-hosted, parrot-echo]
    steps:
      - uses: actions/checkout@master
      - name: Copy files from server folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_KEY }}
          source: "server/*"
          target: "app/server"
